from .orchestrator import ORCHESTRATOR_SYSTEM_PROMPT
from .planning import PLANNING_SYSTEM_PROMPT
from .gmail import GMAIL_SYSTEM_PROMPT
from .news import NEWS_SYSTEM_PROMPT
from .tasks import TASK_SYSTEM_PROMPT
from .calendar import CALENDAR_SYSTEM_PROMPT

__all__ = [
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "PLANNING_SYSTEM_PROMPT",
    "GMAIL_SYSTEM_PROMPT",
    "NEWS_SYSTEM_PROMPT",
    "TASK_SYSTEM_PROMPT",
    "CALENDAR_SYSTEM_PROMPT",
]